feign:
  client:
    config:
      feignName:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: full

hystrix:
 command:
   default:
     execution:
        timeout:
          enabled: false