feign:
  client:
    config:
      feignName:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full

hystrix:
 command:
   default:
     execution:
        timeout:
          enabled: false
        isolation:
          thread:
           timeoutInMilliseconds: 60000